### ISSUE TITLE
All branches of project are fetch even if only one is setup

### ISSUE THREAD

**Issue by gaeljw** [KelkooGroup/theGardener#485]
When trying theGardener on my laptop (via Docker but doesn't matter), I tried to setup theGardener itself as a project inside theGardener.

For that, I used following call to the API to create the project:
```
curl -X POST "http://localhost:9000/api/projects" \
    -H  "accept: application/json" -H  "Content-Type: application/json" \
    -d "{  \"id\": \"theGardener\",  \"name\": \"theGardener\",  \"repositoryUrl\": \"https://github.com/KelkooGroup/theGardener.git\",  \"stableBranch\": \"master\",  \"displayedBranches\": \"master\",  \"featuresRootPath\": \"test/features\",  \"documentationRootPath\": \"documentation\"}"
```
And some other calls to create the hierarchy/link the project.

But after few minutes I still couldn't see the project in the UI. I let it run few hours doing other stuff and I then noticed the following error in the logs:
```
[error] utils.package - Error while cloning repository https://github.com/KelkooGroup/theGardener.git in /git-data/theGardener/renovate/com.typesafe.play-play-json_2.12.8-2.x/
org.eclipse.jgit.api.errors.JGitInternalException: No space left on device
	at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:228)
	at services.GitService.$anonfun$clone$3(GitService.scala:25)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.util.Failure.getOrElse(Try.scala:222)
	at services.GitService.$anonfun$clone$1(GitService.scala:24)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:658)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
Caused by: java.io.IOException: No space left on device
	at java.io.FileOutputStream.writeBytes(Native Method)
	at java.io.FileOutputStream.write(FileOutputStream.java:313)
	at org.eclipse.jgit.lib.ObjectLoader.copyTo(ObjectLoader.java:270)
	at org.eclipse.jgit.dircache.DirCacheCheckout.checkoutEntry(DirCacheCheckout.java:1467)
	at org.eclipse.jgit.dircache.DirCacheCheckout.doCheckout(DirCacheCheckout.java:577)
	at org.eclipse.jgit.dircache.DirCacheCheckout.checkout(DirCacheCheckout.java:484)
	at org.eclipse.jgit.api.CloneCommand.checkout(CloneCommand.java:365)
	at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:225)
	at services.GitService.$anonfun$clone$3(GitService.scala:25)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
error from daemon in stream: Error grabbing logs: unexpected EOF
```

Looking at my disk space, I can see that theGardener used at least 2.4G which is enormous!

This means 2 things:
- theGardener github project is quite big => IMHO there's stuff to clean on the project but it will probably mean rewriting the history and not storing some stuff in it
- :warning:  **the code is actually retrieving all branches of a project even though I just setup the project with the "master" branch** (here it failed when trying to retieve the branch "renovate/com.typesafe.play-play-json_2.12.8-2.x/" as there was no more space left)

**Comment by GeReinhart** [comment]
Indeed it's a bug...
